---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-collection-sno
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/waynedovey/rhoai-policy-collection.git
    path: gitops/applications/policy-collection/overlays/sno
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
