---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: storage-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: storage
      source:
        repoURL: https://github.com/waynedovey/rhoai-policy-collection.git
        path: gitops/applications/storage/overlay/sno
        plugin:
          name: argocd-novault-plugin-kustomize
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
